[#BP-6571]: Move dependent code
JoshLabs/django-livesettings pull request #2
Opened 2018-04-09 14:14 UTC by Naveen1612

2018-04-09 17:20 UTC, arpit-goel requested changes

2018-04-09 17:20 UTC, arpit-goel commented on livesettings/models.py
> +from threaded_multihost import threadlocals
This should be part of its requirements.

2018-04-09 19:01 UTC, Neelakshi1808 commented on livesettings/models.py
> +    updated_through = models.CharField(
Recreate the 0002_migration

2018-04-10 06:36 UTC, Naveen1612 commented on livesettings/models.py
> +    updated_through = models.CharField(
there seem to be no changes in table

2018-04-10 07:49 UTC, arpit-goel approved these changes

2018-04-10 17:53 UTC, Neelakshi1808 commented on livesettings/models.py
> +    updated_through = models.CharField(
in migration we have default datetime for updated at field as default=datetime.datetime(2018, 4, 2, 6, 29, 24, 998104) instead of datetime.datetime.now

2018-04-11 03:55 UTC, merged